Valeria contentful integration
valeriafurin/SewHappy pull request #1
Opened 2021-02-28 17:38 UTC by valeriafurin

Hi there, I integrated Contentful and Apollo and did a proper App set-up.
Please review, thank you!

2021-02-28 17:53 UTC, barsukov requested changes
for the first integration quite good, please delete yarn.lock, and adjust a few comments 👍

2021-02-28 17:53 UTC, barsukov commented on .env
> +export REACT_APP_CONTENTFUL_TOKEN=4J0wH_kob0-C2-7MwgL5JqNJkTLtjDql0TrSJ9gFdCA
Please add .env to .gitignore and since and regenerate the token ;)

2021-02-28 17:53 UTC, barsukov commented on package.json
> +    "apollo-boost": "^0.4.9",
you can delete this package

2021-02-28 17:53 UTC, barsukov commented on src/App.tsx
> +const query = gql`
Please extract this query to own file and reference here

2021-02-28 17:57 UTC, valeriafurin commented on .env
> +export REACT_APP_CONTENTFUL_TOKEN=4J0wH_kob0-C2-7MwgL5JqNJkTLtjDql0TrSJ9gFdCA
Already did that :)

2021-03-01 07:53 UTC, barsukov requested changes

2021-03-01 07:53 UTC, barsukov commented on src/query.tsx
> +export const query = gql`
please name this query regarding the name of the requested data and do not forget to rename the file as well.

2021-03-01 10:55 UTC, valeriafurin commented on src/query.tsx
> +export const query = gql`
Done :)

2021-03-01 11:07 UTC, barsukov approved these changes
👍

2021-03-01 11:53 UTC, merged