Basic layout: Navigation Bar
valeriafurin/SewHappy pull request #5
Opened 2021-03-23 15:02 UTC by valeriafurin

Hi there, 
I built the Navigationbar with a responsive expandable Burgermenu. The Links are not linked yet, will handle that later.

Best

2021-03-26 15:44 UTC, barsukov requested changes
few comments that you can fix before merge but the next task would be nice to integrate the CI pipeline and write your first jest tests.

2021-03-26 15:44 UTC, barsukov commented on src/GlobalStyle.tsx
> +// const sewBox = styled.div`
please delete the comments

2021-03-26 15:44 UTC, barsukov commented on src/components/Burger/Burger.tsx
> +  const clickHandler = () => setOpen(!open);
nice solution 👍

2021-03-26 15:44 UTC, barsukov commented on src/pages/HomePage.tsx
> +      style={{
it is better to use the styled component in this case.

2021-03-26 15:44 UTC, barsukov commented on src/pages/SkirtCalculatorPage.tsx
> +      style={{
please make this div as a styled component

2021-03-26 15:44 UTC, barsukov commented on src/pages/FabricCalculatorPage.tsx
> +      style={{
styled component

2021-03-26 15:44 UTC, barsukov commented on src/pages/AboutPage.tsx
> +      style={{
styled component

2021-03-26 15:50 UTC, valeriafurin commented on src/GlobalStyle.tsx
> +// const sewBox = styled.div`
Sure, forgot to do that

2021-03-26 15:50 UTC, valeriafurin commented on src/components/Burger/Burger.tsx
> +  const clickHandler = () => setOpen(!open);
Thanks!

2021-03-26 15:51 UTC, valeriafurin commented on src/pages/HomePage.tsx
> +      style={{
Alright, will change that. Was not sure about layout, so took this as a placeholder.

2021-03-29 19:59 UTC, barsukov approved these changes
🥇 good work

2021-03-30 08:10 UTC, merged